export interface Product {
  id: string
  image: string
  name: string
  collection: string
  sku: string
  finish: string
  cbm: number
  weight: number
  price: number
  suggestedRetailPrice: number
}

export const products: Product[] = [
  {
    id: "1",
    image: "https://i.postimg.cc/DZBwzmtb/MESA-JADE-RED-BLANCA.jpg",
    name: "Mesa Jade Redonda 105 cm Blanca",
    collection: "Comedor",
    sku: "P54-T43B",
    finish: "Blanco",
    cbm: 0.13,
    weight: 0,
    price: 5835,
    suggestedRetailPrice: 11669,
  },
  {
    id: "2",
    image: "https://i.postimg.cc/HnLM8TYy/MESA-JADE-RED-NEGRA.jpg",
    name: "Mesa Jade Redonda 105 cm Negra",
    collection: "Comedor",
    sku: "P54-T43N",
    finish: "Negro",
    cbm: 0.13,
    weight: 0,
    price: 5835,
    suggestedRetailPrice: 11669,
  },
  {
    id: "3",
    image: "https://i.postimg.cc/J4GJ17dw/MESA-JADE-RECT.jpg",
    name: "Mesa Jade Rectangular 120 cm",
    collection: "Comedor",
    sku: "P54-T31B",
    finish: "Blanco",
    cbm: 0.12,
    weight: 0,
    price: 5345,
    suggestedRetailPrice: 10618,
  },
  {
    id: "4",
    image: "https://i.postimg.cc/DyJW9j8n/MESA-LAVANDA-RED-BLANCA.jpg",
    name: "Mesa Lavanda Redonda 105 cm Blanca",
    collection: "Comedor",
    sku: "P45-T43B",
    finish: "Blanco",
    cbm: 0.13,
    weight: 0,
    price: 6700,
    suggestedRetailPrice: 13625,
  },
  {
    id: "5",
    image: "https://i.postimg.cc/C1x5mJ3y/MESA-LAVANDA-RED-NEGRA.jpg",
    name: "Mesa Lavanda Redonda 105 cm Negra",
    collection: "Comedor",
    sku: "P45-T43N",
    finish: "Negro",
    cbm: 0.13,
    weight: 0,
    price: 6700,
    suggestedRetailPrice: 13625,
  },
  {
    id: "6",
    image: "https://i.postimg.cc/k4Y4ZKC2/MESA-LAVANDA-RECT.jpg",
    name: "Mesa Lavanda Rectangular 120 cm",
    collection: "Comedor",
    sku: "P45-T31B",
    finish: "Blanco",
    cbm: 0.12,
    weight: 0,
    price: 6210,
    suggestedRetailPrice: 12574,
  },
  {
    id: "7",
    image: "https://i.postimg.cc/bw0vPK8c/MESA-ELMA-RED-BLANCA.jpg",
    name: "Mesa Elma Redonda 105 cm",
    collection: "Comedor",
    sku: "P002-T43B",
    finish: "Blanco",
    cbm: 0.42,
    weight: 0,
    price: 9203,
    suggestedRetailPrice: 15823,
  },
  {
    id: "8",
    image: "https://i.postimg.cc/t7QXQzM4/MESA-ELMA-RECT.jpg",
    name: "Mesa Elma Rectangular 120 cm",
    collection: "Comedor",
    sku: "P002-T31B",
    finish: "Blanco",
    cbm: 0.42,
    weight: 0,
    price: 8714,
    suggestedRetailPrice: 14772,
  },
  {
    id: "9",
    image: "https://i.postimg.cc/h4HxtRFf/MESA-ELMA-RECT-120.jpg",
    name: "Mesa Elma Reforzada Rectangular 120 cm",
    collection: "Comedor",
    sku: "P010-T31B",
    finish: "Blanco",
    cbm: 0.61,
    weight: 0,
    price: 10487,
    suggestedRetailPrice: 19817,
  },
  {
    id: "10",
    image: "https://i.postimg.cc/9fMzBL36/MESA-PETRA.jpg",
    name: "Mesa Petra Rectangular 160 cm",
    collection: "Comedor",
    sku: "P008-T26B",
    finish: "Blanco",
    cbm: 0.18,
    weight: 0,
    price: 11851,
    suggestedRetailPrice: 24549,
  },
  {
    id: "11",
    image: "https://i.postimg.cc/L63XKcmd/SILLA-LOLA.jpg",
    name: "SILLAS LOLA LINO CAQUI (TELLA BEIGE)",
    collection: "Comedor",
    sku: "CMM004CA",
    finish: "Beige",
    cbm: 0.34,
    weight: 0,
    price: 3742,
    suggestedRetailPrice: 6436,
  },
  {
    id: "12",
    image: "https://i.postimg.cc/13Rz9vz8/SILLA-ALICE.jpg",
    name: "SILLAS ALICE LINO GRIS MEZCLADO",
    collection: "Comedor",
    sku: "CMM006CA",
    finish: "Gris",
    cbm: 0.34,
    weight: 0,
    price: 4051,
    suggestedRetailPrice: 7131,
  },
  {
    id: "13",
    image: "https://i.postimg.cc/NMXsNVdz/colchon-1p-ml.jpg",
    name: "Colchon 1 PLAZA",
    collection: "Dormitorio",
    sku: "C088",
    finish: "gris",
    cbm: 0.31,
    weight: 0,
    price: 6459,
    suggestedRetailPrice: 10915,
  },
  {
    id: "14",
    image: "https://i.postimg.cc/KjyZCNVv/colchon-2p-ml.jpg",
    name: "Colchon 2 PLAZA",
    collection: "Dormitorio",
    sku: "C138",
    finish: "gris",
    cbm: 0.49,
    weight: 0,
    price: 9305,
    suggestedRetailPrice: 15262,
  },
  {
    id: "15",
    image: "https://i.postimg.cc/VkNYy57M/colchon-queen-ml.jpg",
    name: "Colchon QUEEN",
    collection: "Dormitorio",
    sku: "C158",
    finish: "gris",
    cbm: 0.59,
    weight: 0,
    price: 11110,
    suggestedRetailPrice: 18153,
  },
  {
    id: "16",
    image: "https://i.postimg.cc/vmgbBkwZ/E7-PROBF50.jpg",
    name: "BOX BAUL 1 PLAZA",
    collection: "Dormitorio",
    sku: "BAU088",
    finish: "gris",
    cbm: 0.50,
    weight: 0,
    price: 8169,
    suggestedRetailPrice: 14405,
  },
  {
    id: "17",
    image: "https://i.postimg.cc/q7P0CwpX/2p.jpg",
    name: "BOX BAUL 2 PLAZAS",
    collection: "Dormitorio",
    sku: "BAU138",
    finish: "gris",
    cbm: 0.78,
    weight: 0,
    price: 10680,
    suggestedRetailPrice: 27240,
  },
  {
    id: "18",
    image: "https://i.postimg.cc/0Q7vGSQg/BOX-Q1.png",
    name: "BOX BAUL QUEEN",
    collection: "Dormitorio",
    sku: "BAU158",
    finish: "gris",
    cbm: 0.94,
    weight: 0,
    price: 15827,
    suggestedRetailPrice: 29423,
  },
  {
    id: "19",
    image: "https://i.postimg.cc/fLQnbbv8/MB-1003-Mel-FIResultado-700x700.png",
    name: "RACK PARA TV HOGAR 135CM",
    collection: "LIVING",
    sku: "MB 1003",
    finish: "Blanco",
    cbm: 0.06,
    weight: 0,
    price: 4394,
    suggestedRetailPrice: 5493,
  },
  {
    id: "20",
    image: "https://i.postimg.cc/rmNbFNsp/MB-1001-ML.jpg",
    name: "APARADOR BUFFET 80CM",
    collection: "LIVING",
    sku: "MB 1001",
    finish: "Blanco",
    cbm: 0.06,
    weight: 0,
    price: 4243,
    suggestedRetailPrice: 6790,
  },
  {
    id: "21",
    image: "https://i.postimg.cc/Gt0kNWd8/MB-1002-FI-R1-Off-White-Resultado-700x700.png",
    name: "APARADOR BUFFET 119,4CM",
    collection: "LIVING",
    sku: "MB 1002",
    finish: "Blanco",
    cbm: 0.08,
    weight: 0,
    price: 5632,
    suggestedRetailPrice: 7990,
  },
  {
    id: "22",
    image: "https://i.postimg.cc/fyxxh8RH/MB-1057.jpg",
    name: "Vitrina de cristal con 2 puertas y 1 cajón",
    collection: "LIVING",
    sku: "MB 1057",
    finish: "Blanco",
    cbm: 0.11,
    weight: 0,
    price: 7171,
    suggestedRetailPrice: 9490,
  },
  {
    id: "23",
    image: "https://i.postimg.cc/7P717Zng/MB-1005.jpg",
    name: "Vitrina retro de cristal de 70 cm",
    collection: "LIVING",
    sku: "MB 1005",
    finish: "Blanco",
    cbm: 0.09,
    weight: 0,
    price: 6750,
    suggestedRetailPrice: 9490,
  },
  {
    id: "24",
    image: "https://i.postimg.cc/vHtWq2jT/MB-1060-Mel-Off-White-FI-700x700.png",
    name: "Escritorio Nórdico 120cm Con Estante",
    collection: "OFICINA",
    sku: "MB 1060",
    finish: "blanco / miel",
    cbm: 0.05,
    weight: 0,
    price: 2779,
    suggestedRetailPrice: 3690,
  },
  {
    id: "25",
    image: "https://i.postimg.cc/G3J8d8jS/MSM-439.jpg",
    name: "Escritorio Para PC 120 cm Con Cajones",
    collection: "OFICINA",
    sku: "MSM 439",
    finish: "blanco",
    cbm: 0.05,
    weight: 0,
    price: 3077,
    suggestedRetailPrice: 3846,
  },
  {
    id: "26",
    image: "https://i.postimg.cc/fTz3Lz2W/MSM-421.jpg",
    name: "Escritorio Diseño 90 cm Con Cajón Logrado",
    collection: "OFICINA",
    sku: "MSM 421",
    finish: "miel",
    cbm: 0.04,
    weight: 0,
    price: 2626,
    suggestedRetailPrice: 3283,
  },
  {
    id: "27",
    image: "https://i.postimg.cc/brCqdhrd/MB-1059-MIEL-P.jpg",
    name: "Cómoda con 4 cajones y 1 puerta",
    collection: "LIVING",
    sku: "MB 1059 M",
    finish: "miel",
    cbm: 0.08,
    weight: 0,
    price: 5361,
    suggestedRetailPrice: 6790,
  },
  {
    id: "28",
    image: "https://i.postimg.cc/Xq7VVJVT/MB-1059-BLANCO-MIEL.jpg",
    name: "Cómoda con 4 cajones y 1 puerta",
    collection: "LIVING",
    sku: "MB 1059 B",
    finish: "blanco",
    cbm: 0.08,
    weight: 0,
    price: 5361,
    suggestedRetailPrice: 6790,
  },
  {
    id: "29",
    image: "https://i.postimg.cc/HWBY6QzH/RT-3151.png",
    name: "Vitrina de cristal con 2 puertas y 2 cajones",
    collection: "LIVING",
    sku: "RT 3151",
    finish: "blanco",
    cbm: 0.11,
    weight: 0,
    price: 7300,
    suggestedRetailPrice: 9490,
  },
  {
    id: "30",
    image: "https://i.postimg.cc/GhfcCd65/MB-1046-ML.jpg",
    name: "Mostrador retro con 1 puerta y 1 cajón",
    collection: "LIVING",
    sku: "MB 1046",
    finish: "blanco",
    cbm: 0.04,
    weight: 0,
    price: 2545,
    suggestedRetailPrice: 3181,
  },
  {
    id: "31",
    image: "https://i.postimg.cc/761gFB6K/milan-blanca.webp",
    name: "Silla  Milan Belloch Blanco",
    collection: "Comedor",
    sku: "HC -P70B",
    finish: "blanco",
    cbm: 0.04,
    weight: 0,
    price: 1319,
    suggestedRetailPrice: 1649,
  },
  {
    id: "32",
    image: "https://i.postimg.cc/8Pm0RHmB/silla-milan.jpg",
    name: "Silla Millan Belloch Negra",
    collection: "Comedor",
    sku: "HC -P70N",
    finish: "Negro",
    cbm: 0.04,
    weight: 0,
    price: 1319,
    suggestedRetailPrice: 1649,
  },
  {
    id: "33",
    image: "https://i.postimg.cc/T19B3qk9/bco.jpg",
    name: "Sillas Gruvyer Blanco",
    collection: "Comedor",
    sku: "HC-N06B",
    finish: "blanco",
    cbm: 0.04,
    weight: 0,
    price: 1026,
    suggestedRetailPrice: 1283,
  },
  {
    id: "34",
    image: "https://i.postimg.cc/15vLxBVR/100px-10.jpg",
    name: "Sillas Gruvyer Negro",
    collection: "Comedor",
    sku: "HC-N06N",
    finish: "negro",
    cbm: 0.04,
    weight: 0,
    price: 1026,
    suggestedRetailPrice: 1283,
  },
  {
    id: "35",
    image: "https://i.postimg.cc/fbm2bfy9/blanca.jpg",
    name: "Silla Aurora Marcela Blanca",
    collection: "Comedor",
    sku: "HC-N50B",
    finish: "blanca",
    cbm: 0.06,
    weight: 0,
    price: 1677,
    suggestedRetailPrice: 2096,
  },
  {
    id: "36",
    image: "https://i.postimg.cc/dVzNvxsF/beige.jpg",
    name: "Silla Aurora Marcela Beige",
    collection: "Comedor",
    sku: "HC-N50C",
    finish: "beige",
    cbm: 0.06,
    weight: 0,
    price: 1677,
    suggestedRetailPrice: 2096,
  },
  {
    id: "37",
    image: "https://i.postimg.cc/yNym5QWv/aurora-negr.jpg",
    name: "Silla Aurora Marcela Negra",
    collection: "Comedor",
    sku: "HC-N50N",
    finish: "negro",
    cbm: 0.06,
    weight: 0,
    price: 1677,
    suggestedRetailPrice: 2096,
  },
  {
    id: "38",
    image: "https://i.postimg.cc/3RJvq2yG/HC-P101.webp",
    name: "Silla Plia Umea",
    collection: "Comedor",
    sku: "HC-P101",
    finish: "transparente",
    cbm: 0.02,
    weight: 0,
    price: 1204,
    suggestedRetailPrice: 3990,
  },
  {
    id: "39",
    image: "https://i.postimg.cc/N010xFpH/blanca.webp",
    name: "Mesa Eames Redonda Laqueada 100cm Blanco",
    collection: "Comedor",
    sku: "HT -M01B",
    finish: "blanco",
    cbm: 0.11,
    weight: 0,
    price: 3432.09,
    suggestedRetailPrice: 6500,
  },
  {
    id: "40",
    image: "https://i.postimg.cc/wv2TSPKx/negra.webp",
    name: "Mesa Eames Redonda Laqueada 100cm Negro",
    collection: "Comedor",
    sku: "HT -M01N",
    finish: "negro",
    cbm: 0.11,
    weight: 0,
    price: 3432.09,
    suggestedRetailPrice: 6500,
  },
  {
    id: "41",
    image: "https://i.postimg.cc/x8FjdzTW/Mesaeamesvidrio90.webp",
    name: "Mesa Eames Redonda Vidrio 90cm",
    collection: "Comedor",
    sku: "HT -G019",
    finish: "transparente",
    cbm: 0.09,
    weight: 0,
    price: 3258.17,
    suggestedRetailPrice: 5999,
  },
  {
    id: "42",
    image: "https://i.postimg.cc/yNXVZ58h/eames-vidrio-100.webp",
    name: "Mesa Eames Redonda Vidrio 100cm",
    collection: "Comedor",
    sku: "HT -G01",
    finish: "transparente",
    cbm: 0.11,
    weight: 0,
    price: 3875.89,
    suggestedRetailPrice: 6950,
  },
  {
    id: "43",
    image: "https://i.postimg.cc/XJs42CFp/HT-M08-BLANCA.webp",
    name: "Mesa Eames Rectangular Laqueada 120cm",
    collection: "Comedor",
    sku: "HT -M08B",
    finish: "blanca",
    cbm: 0.17,
    weight: 0,
    price: 4781,
    suggestedRetailPrice: 8100,
  },
  {
    id: "44",
    image: "https://i.postimg.cc/k5w09d5H/plia.webp",
    name: "Mesa Plia Umea",
    collection: "Comedor",
    sku: "HT-P04",
    finish: "transparente",
    cbm: 0.03,
    weight: 0,
    price: 2899,
    suggestedRetailPrice: 6500,
  },
  {
    id: "45",
    image: "https://i.postimg.cc/MHdy9dZg/HT-M64-BLANCA.webp",
    name: "Mesa Eames Rectangular Laqueada 100 cm",
    collection: "OFICINA",
    sku: "HT-M64B",
    finish: "Blanca",
    cbm: 0.08,
    weight: 0,
    price: 3425,
    suggestedRetailPrice: 4281,
  },
  {
    id: "46",
    image: "https://i.postimg.cc/d0QDBdST/HT-M04-BLANCA.webp",
    name: "Mesa  Milan Cuadrada Laqueada 80 cm Blanca",
    collection: "Comedor",
    sku: "HT-M04B",
    finish: "Blanco",
    cbm: 0.12,
    weight: 0,
    price: 4456,
    suggestedRetailPrice: 5570,
  },
  {
    id: "47",
    image: "https://i.postimg.cc/Y9YcLDfN/HT-M04-NEGRA.webp",
    name: "Mesa  Milan Cuadrada Laqueada 80 cm Negra",
    collection: "Comedor",
    sku: "HT-M04N",
    finish: "negro",
    cbm: 0.12,
    weight: 0,
    price: 4456,
    suggestedRetailPrice: 5570,
  },
  {
    id: "48",
    image: "https://i.postimg.cc/50SVkkY4/milan-red-b.jpg",
    name: "Mesa Milan Redonda Laqueada 80cm Blanca",
    collection: "Comedor",
    sku: "HT-M06B",
    finish: "blanco",
    cbm: 0.12,
    weight: 0,
    price: 4456,
    suggestedRetailPrice: 5570,
  },
  {
    id: "49",
    image: "https://i.postimg.cc/BbRM5JSX/HT-M06-NEGRA.webp",
    name: "Mesa Milan Redonda Laqueada 80cm Negra",
    collection: "Comedor",
    sku: "HT-M06N",
    finish: "negro",
    cbm: 0.12,
    weight: 0,
    price: 4456,
    suggestedRetailPrice: 5570,
  }
]

